CREATE TABLE autores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    nacionalidade VARCHAR(100),
    biografia TEXT,
    data_nascimento DATE,
    data_falecimento DATE,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE editoras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE,
    nacionalidade VARCHAR(100),
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE filiais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia VARCHAR(150) NOT NULL,
    razao_social VARCHAR(150) NOT NULL,
    endereco VARCHAR(200) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(100),
    numero VARCHAR(10),
    telefone VARCHAR(15),
    inscricao_estadual VARCHAR(20),
    complemento VARCHAR(100),
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE generos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE estantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    localizacao VARCHAR(150) NOT NULL,
    capacidade INTEGER,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE gestores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    matricula_funcionario VARCHAR(20) NOT NULL UNIQUE,
    filial_id BIGINT NOT NULL REFERENCES filiais(id),
    ultimo_acesso TIMESTAMP WITH TIME ZONE,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    telefone VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    filial_id BIGINT NOT NULL REFERENCES filiais(id),
    endereco VARCHAR(150),
    cidade VARCHAR(100),
    bairro VARCHAR(100),
    estado VARCHAR(2),
    cep VARCHAR(8),
    numero VARCHAR(10),
    limite_livros INTEGER DEFAULT 3,
    esta_bloqueado BOOLEAN DEFAULT FALSE,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE materiais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) CHECK (tipo IN ('LIVRO', 'PERIODICO', 'OUTROS')),
    subtitulo VARCHAR(255),
    sinopse TEXT,
    issn VARCHAR(20),
    tema VARCHAR(255),
    descricao TEXT,
    observacao TEXT,
    isbn VARCHAR(13) UNIQUE,
    edicao INTEGER DEFAULT 1,
    ano_publicacao INTEGER,
    quantidade_paginas INTEGER,
    editora_id BIGINT NOT NULL REFERENCES editoras(id),
    autor_id BIGINT REFERENCES autores(id),
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE materiais_autores (
    autor_id BIGINT NOT NULL REFERENCES autores(id),
    material_id BIGINT NOT NULL REFERENCES materiais(id),
    PRIMARY KEY (autor_id, material_id)
);

CREATE TABLE materiais_generos (
    genero_id BIGINT NOT NULL REFERENCES generos(id),
    material_id BIGINT NOT NULL REFERENCES materiais(id),
    PRIMARY KEY (genero_id, material_id)
);

CREATE TABLE exemplares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES materiais(id),
    filial_id BIGINT NOT NULL REFERENCES filiais(id),
    estante_id BIGINT NOT NULL REFERENCES estantes(id),
    prateleira VARCHAR(50),
    posicao VARCHAR(50),
    codigo_barras VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR DEFAULT 'DISPONIVEL' CHECK (status IN ('DISPONIVEL', 'EMPRESTADO', 'RESERVADO', 'MANUTENCAO', 'EXTRAVIADO')),
    data_aquisicao DATE,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE emprestimos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exemplar_id BIGINT NOT NULL REFERENCES exemplares(id),
    gestor_id BIGINT NOT NULL REFERENCES gestores(id),
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    data_saida TIMESTAMP WITH TIME ZONE,
    data_devolucao_prevista DATE NOT NULL,
    renovacoes_contagem INTEGER DEFAULT 0,
    data_devolucao_efetivada TIMESTAMP WITH TIME ZONE,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE historico_multas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emprestimo_id BIGINT NOT NULL REFERENCES emprestimos(id),
    dias_atraso INTEGER NOT NULL,
    valor NUMERIC(10, 2) NOT NULL,
    pago BOOLEAN DEFAULT FALSE,
    data_pagamento DATE,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE lista_tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gestor_id BIGINT NOT NULL REFERENCES gestores(id),
    descricao VARCHAR(255) NOT NULL,
    prioridade VARCHAR DEFAULT 'MEDIA' CHECK (prioridade IN ('BAIXA', 'MEDIA', 'ALTA', 'URGENTE')),
    concluida BOOLEAN DEFAULT FALSE,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE
);

CREATE TABLE configuracoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filial_id BIGINT NOT NULL REFERENCES filiais(id),
    chave VARCHAR(50) NOT NULL,
    descricao VARCHAR(255),
    valor TEXT NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    excluido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP WITH TIME ZONE,
    data_ultima_atualizacao TIMESTAMP WITH TIME ZONE,
    UNIQUE (filial_id, chave)
);
