spring.application.name=mylibrum
# ===============================
# CONFIGURAÇÕES DO POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/librumDb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# Mostra no console as consultas SQL geradas pelo Hibernate (útil para debug)
spring.jpa.show-sql=true

# Atualiza o esquema do banco de dados automaticamente (use 'update' para dev e 'validate' ou 'none' para produção)
spring.jpa.hibernate.ddl-auto=update

# Define o dialeto do PostgreSQL para o Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect